theme: jekyll-theme-cayman
plugins:
  - jekyll-menus
  - jekyll-redirect-from
collections:
  docs:
    output: true
    permalink: /:collection/:path/
categories-order:
  - about
  - getting started
  - guides
  - element