site_name: IXOCREATE
docs_dir: 'docs/'
site_dir: '../_site'
theme:
  name: null
  custom_dir: 'ixocreate_theme/'
  highlightjs: true
  hljs_style: dracula
  hljs_languages:
    - php
    - bash
nav:
  - 'Getting Started':
      - 'Installation': 'getting-started/installation.md'
      - 'Directory Structure': 'getting-started/directory-structure.md'
      - 'Create PageTypes': 'getting-started/page-type.md'
      - 'Create Blocks': 'getting-started/block.md'
      - 'Templates': 'getting-started/template.md'
  - 'Components':
      - 'Schema': 'components/schema.md'
      - 'Page Types': 'components/page-types.md'
      - 'Blocks': 'components/blocks.md'
      - 'Resources': 'components/resources.md'
      - 'Servicemanager': 'components/servicemanager.md'
      - 'Collection': 'components/collection.md'
      - 'Command Bus': 'components/command-bus.md'
      - 'Cache': 'components/cache.md'
      - 'Events': 'components/events.md'
  - 'Guides':
      - 'Configuration': 'guides/configuration.md'
      - 'Command Line': 'guides/cli.md'
      - 'Performance': 'guides/performance.md'
      - 'Deployment': 'guides/deployment.md'
      - 'Packages': 'guides/packages.md'
      - 'Custom admin': 'guides/custom-admin.md'
  - 'Concept':
      - 'Request Lifecycle': 'concept/request-lifecycle.md'
      - 'Types': 'concept/types.md'

